from utils import tratar_none, tratar_tiny

def tranforma_dados_agente_cliente(item):
    return{
    'codigoSistema' : tratar_none(item.get("codigoSistema")),
    'tipoOrganizacao' : tratar_none(item.get("tipoOrganizacao")),
    'isEnquadraIPI' : tratar_none(tratar_tiny(item.get("isEnquadraIPI"))),
    'isEnquadraICMS' : tratar_none(tratar_tiny(item.get("isEnquadraICMS"))),
    'isEnquadraISS' : tratar_none(tratar_tiny(item.get("isEnquadraISS"))),
    'statusCNPJ' : tratar_none(item.get("statusCNPJ")),
    'isIPISimples' : tratar_none(tratar_tiny(item.get("isIPISimples"))),
    'isICMSSimples' : tratar_none(tratar_tiny(item.get("isICMSSimples"))),
    'isISSSimples' : tratar_none(tratar_tiny(item.get("isISSSimples"))),
    'isSimplesNacional' : tratar_none(tratar_tiny(item.get("isSimplesNacional"))),
    'formaPagamento' : tratar_none(item.get("formaPagamento"), tipo="int"),
    'ultimaAtualizacao' : tratar_none(item.get("ultimaAtualizacao")),
    'validadeCadastro' : tratar_none(item.get("validadeCadastro"), tipo="int"),
    'tipoInscricao' : tratar_none(item.get("tipoInscricao")),
    'isRetemIR' : tratar_none(item.get("isRetemIR")),
    'isRetemINSS' : tratar_none(item.get("isRetemINSS")),
    'codigoIbge' : tratar_none(item.get("codigoIbge")),
    'nomeFantasia' : tratar_none(item.get("nomeFantasia")),
    'nomeAgente' : tratar_none(item.get("nomeAgente")),
    'tipoInscricaoESocial' : tratar_none(item.get("tipoInscricaoESocial")),
    'tipoPessoa' : tratar_none(item.get("tipoPessoa")),
    'tipoPessoaRural' : tratar_none(item.get("tipoPessoaRural")),
    'isFluxoCaixa' : tratar_none(tratar_tiny(item.get("isFluxoCaixa"))),
    'naturezaJuridica' : tratar_none(item.get("naturezaJuridica")),
    'codigoCNAE' : tratar_none(item.get("codigoCNAE")),
    'email' : tratar_none(item.get("email")),
    'paisSigla' : tratar_none(item.get("paisSigla")),
    'ufSigla' : tratar_none(item.get("ufSigla")),
    'enquadramentoEmpresa' : tratar_none(item.get("enquadramentoEmpresa")),
    'inscricaoEstadual' : tratar_none(tratar_tiny(item.get("inscricaoEstadual"))),
    'inscricaoMunicipal' : tratar_none(tratar_tiny(item.get("inscricaoMunicipal"))),
    'codigoCEI' : tratar_none(item.get("codigoCEI")),
    'cnpj' : tratar_none(item.get("cnpj")),
    'codigoMunicipio' : tratar_none(item.get("codigoMunicipio"), tipo="int"),
    'tipoLogradouro' : tratar_none(item.get("tipoLogradouro")),
    'nomeLogradouro' : tratar_none(item.get("nomeLogradouro")),
    'numeroEndereco' : tratar_none(item.get("numeroEndereco")),
    'bairro' : tratar_none(item.get("bairro")),
    'cep' : tratar_none(item.get("cep")),
    'complementoEndereco' : tratar_none(item.get("complementoEndereco")),
    'referenciaEndereco' : tratar_none(item.get("referenciaEndereco")),
    'isOrgaoPublico' : tratar_none(tratar_tiny(item.get("isOrgaoPublico"))),
    'tipoDespAduaneira' : tratar_none(item.get("tipoDespAduaneira")),
    'fretePesoValor' : tratar_none(item.get("fretePesoValor")),
    'isDispensadoNIF' : tratar_none(item.get("isDispensadoNIF")),
    }